import {
  DashboardMobileNav,
  DashboardNav,
  DashboardTopNav
} from '@/components/ui/Shared';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function DashboardLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={inter.className}>
      <DashboardMobileNav />
      <DashboardNav />
      <div className="lg:pl-72">
        <div>
          <DashboardTopNav />
        </div>
        {/* <main className="py-10">
          <div className="px-4 sm:px-6 lg:px-8">{children}</div>
        </main> */}
        <main>
          <div>{children}</div>
        </main>
      </div>
    </div>
  );
}
